### ISSUE TITLE
哈喽，能不能给一个初始化数据库

### ISSUE THREAD

**Issue by fanyiqiang2015** [iUndeined/leave_sys#1]
你好，我想学习一下，你这个，但是没有初始数据库，只有表结构，所以不知道怎么添加admin，无法登录
也不法注册 QQ:1530896000

**Comment by iUndeined** [comment]
晚些时候我再将数据库初始化脚本同步上来吧.

**Comment by fanyiqiang2015** [comment]
非常感谢

**Comment by iUndeined** [comment]
@fanyiqiang2015 根目录下 leave_sys_setup.sql ，自己建一个数据库utf-8编码，把脚本导进去就行，地址在配置文件 src/config.txt 里修改。
